import { useCallback, useEffect, useState } from "react";
import { Pressable, Share, Text, View } from "react-native";
import { authPost, get } from "../lib/api";
import { Action, Card, colors, ErrorBanner, Eyebrow, Field, Loading, Pill, Screen, Title } from "../lib/ui";

type Delivery = { channel: "sms" | "email"; status: "queued" | "failed" | "not_configured"; message: string };
type Guardian = { id: string; name: string; relationship: string; phone?: string; email?: string; priority: number; status: string; invite_token: string; invite_expires_at: string; journey_started: boolean; missed_checkin: boolean; sos: boolean; live_location: boolean; delivery?: Delivery[] };
type DeliveryResponse = { invite_url: string; deliveries: Delivery[] };

function ChannelChoice({ selected, icon, label, detail, onPress }: { selected: boolean; icon: string; label: string; detail: string; onPress: () => void }) {
  return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selected }} onPress={onPress} style={{ flex: 1, minWidth: 145, minHeight: 72, padding: 13, borderRadius: 16, borderWidth: 2, borderColor: selected ? colors.primary : colors.border, backgroundColor: selected ? colors.mint : "white", justifyContent: "center" }}><Text style={{ color: colors.ink, fontWeight: "900" }}>{selected ? "✓ " : ""}{icon} {label}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 4 }}>{detail}</Text></Pressable>;
}

export default function Guardians() {
  const [items, setItems] = useState<Guardian[]>([]); const [name, setName] = useState(""); const [relationship, setRelationship] = useState("Friend"); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [sms, setSms] = useState(true); const [mail, setMail] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { const data = await get<{ guardians: Guardian[] }>("/guardians"); setItems(data.guardians); } catch (e) { setError(e instanceof Error ? e.message : "Could not load guardians"); } }, []);
  useEffect(() => { load(); }, [load]);
  async function addAndSend() { try { setBusy(true); setError(""); setNotice(""); const channels = [...(sms ? ["sms" as const] : []), ...(mail ? ["email" as const] : [])]; const created = await authPost<Guardian>("/guardians", { name: name.trim(), relationship: relationship.trim(), phone: phone.trim() || null, email: email.trim() || null, priority: Math.min(items.length + 1, 5), journey_started: true, missed_checkin: true, sos: true, live_location: true }); const result = await authPost<DeliveryResponse>(`/guardians/${created.id}/send-invite`, { channels }); const guardian = { ...created, delivery: result.deliveries, status: result.deliveries.some(d => d.status === "queued") ? "invite sent" : "delivery needs setup" }; setItems(value => [...value, guardian]); setName(""); setPhone(""); setEmail(""); setNotice(result.deliveries.map(d => `${d.channel.toUpperCase()}: ${d.message}`).join(" ")); } catch (e) { setError(e instanceof Error ? e.message : "Could not send invitation"); } finally { setBusy(false); } }
  async function shareInvite(g: Guardian) { const appBase = process.env.EXPO_PUBLIC_APP_URL || (typeof window !== "undefined" ? window.location.origin : "https://shakti360.app"); await Share.share({ title: "Shakti360 Guardian invitation", message: `${g.name}, you’re invited to be a temporary safety guardian. ${appBase}/guardian-invite?token=${g.invite_token}\nExpires ${new Date(g.invite_expires_at).toLocaleString()}` }); }
  const valid = name.trim() && (sms || mail) && (!sms || phone.trim()) && (!mail || email.trim());
  return <Screen><Eyebrow>TRUSTED GUARDIAN CIRCLE</Eyebrow><Title subtitle="You decide who receives journey, missed check-in, SOS, and temporary location updates.">People you trust</Title><Card tone="mint"><Text style={{ color: colors.primaryDark, fontWeight: "900" }}>Session-based, never permanent</Text><Text style={{ color: colors.muted, lineHeight: 20 }}>Invitation links expire after 24 hours. Location access expires after each safety session.</Text></Card>
    {items.map((g, index) => <Card key={g.id}><View style={{ flexDirection: "row", justifyContent: "space-between", gap: 10 }}><View style={{ flex: 1 }}><Text style={{ color: colors.ink, fontWeight: "900", fontSize: 17 }}>{g.name}</Text><Text style={{ color: colors.muted }}>{g.relationship} • Priority {index + 1}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 3 }}>{g.phone || g.email || "Share link only"}</Text></View><Pill label={g.status} tone={g.status === "invite sent" ? "green" : "gold"} /></View>{g.delivery?.map(d => <Text key={d.channel} style={{ color: d.status === "queued" ? colors.primary : colors.gold, fontSize: 13, fontWeight: "700" }}>{d.channel === "sms" ? "SMS" : "Email"}: {d.message}</Text>)}<Text style={{ color: colors.muted, lineHeight: 20 }}>Receives: journey start • missed check-in • SOS • temporary location</Text><Action label="Share invitation another way" icon="share" variant="secondary" onPress={() => shareInvite(g)} /></Card>)}
    <Card><Text style={{ color: colors.ink, fontWeight: "900", fontSize: 20 }}>Add and invite a guardian</Text><Text style={{ color: colors.muted, lineHeight: 20 }}>Choose exactly how you want this invitation delivered.</Text><Field label="Name" value={name} onChangeText={setName} placeholder="Guardian name" autoComplete="name" /><Field label="Relationship" value={relationship} onChangeText={setRelationship} placeholder="Friend, parent, partner…" /><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 10 }}><ChannelChoice selected={sms} icon="💬" label="Text message" detail="Delivered with Twilio" onPress={() => setSms(v => !v)} /><ChannelChoice selected={mail} icon="✉️" label="Email" detail="Delivered with Resend" onPress={() => setMail(v => !v)} /></View>{sms ? <Field label="Mobile number" value={phone} onChangeText={setPhone} placeholder="+1 555 123 4567" keyboardType="phone-pad" autoComplete="tel" /> : null}{mail ? <Field label="Email address" value={email} onChangeText={setEmail} placeholder="guardian@example.com" keyboardType="email-address" autoCapitalize="none" autoComplete="email" /> : null}<Text style={{ color: colors.muted, fontSize: 12 }}>Use an international phone number beginning with + and country code.</Text><Action label="Send secure invitation" icon="send" onPress={addAndSend} disabled={busy || !valid} /></Card>{busy ? <Loading label="Sending through secure delivery providers…" /> : null}{notice ? <Card tone="mint"><Text style={{ color: colors.primaryDark, lineHeight: 20, fontWeight: "700" }}>{notice}</Text></Card> : null}{error ? <ErrorBanner message={error} retry={load} /> : null}<Text style={{ color: colors.muted, fontSize: 12, lineHeight: 18 }}>“Queued” means the provider accepted the message, not that the recipient opened it. Carrier and mailbox delivery can still fail.</Text></Screen>;
}
