import { useEffect, useState } from "react";
import { Text, View } from "react-native";
import * as Battery from "expo-battery";
import { authPost, post } from "../lib/api";
import { Action, Card, colors, ErrorBanner, Eyebrow, Field, Loading, Metric, Pill, Screen, Title } from "../lib/ui";
import { queueNonSensitiveEvent, readLocal, removeLocal, storageKeys, writeLocal } from "../lib/storage";

type Journey = { id: string; origin: string; destination: string; started_at: string; expected_arrival: string; battery_percent: number; power_mode: string; missed_checkins: number; escalation_level: string; active: boolean };
type BatteryPolicy = { desired_accuracy: string; time_interval_s: number; tracking_enabled: boolean; estimated_impact: string; reason: string; policy_version: string };
export default function JourneyScreen() {
  const [origin, setOrigin] = useState("Campus library"); const [destination, setDestination] = useState("Home");
  const [journey, setJourney] = useState<Journey | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [batteryPolicy, setBatteryPolicy] = useState<BatteryPolicy | null>(null);
  const [restored, setRestored] = useState(false);
  useEffect(() => { readLocal<{ journey: Journey; batteryPolicy: BatteryPolicy | null }>(storageKeys.activeJourney).then(saved => { if (saved?.journey.active) { setJourney(saved.journey); setBatteryPolicy(saved.batteryPolicy); setNotice("Active journey recovered from this device. Confirm server status before relying on live updates."); } setRestored(true); }); }, []);
  useEffect(() => { if (!restored || !journey) return; if (journey.active) writeLocal(storageKeys.activeJourney, { journey, batteryPolicy }); else removeLocal(storageKeys.activeJourney); }, [journey, batteryPolicy, restored]);
  async function act(task: () => Promise<void>) { try { setBusy(true); setError(""); await task(); } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong"); } finally { setBusy(false); } }
  const start = () => act(async () => { const level = await Battery.getBatteryLevelAsync(); const battery = level < 0 ? 50 : Math.round(level * 100); const [data, policy] = await Promise.all([post<Journey>("/journeys", { origin: origin.trim(), destination: destination.trim(), eta_minutes: 10, battery_percent: battery, trusted_contacts: ["Trusted Contact"] }), post<BatteryPolicy>("/battery/policy", { battery_level: battery, charging: false, movement_state: "moving", journey_state: "active", risk_state: "normal", time_since_location_s: 0, distance_moved_m: 0 })]); await authPost("/guardians/notify", { event: "journey_started", journey_id: data.id, message: `Journey started from ${data.origin} to ${data.destination}. Expected arrival ${new Date(data.expected_arrival).toLocaleTimeString()}.` }); setJourney(data); setBatteryPolicy(policy); setNotice("Journey protection is active. Guardian notifications were submitted through your configured providers."); });
  const checkin = (arrived: boolean) => act(async () => { if (!journey) return; const data = await post<{ journey: Journey }>("/journeys/checkin", { journey_id: journey.id, arrived }); await authPost("/guardians/notify", { event: arrived ? "journey_completed" : "missed_checkin", journey_id: journey.id }); setJourney(data.journey); if (arrived) { const completedAt = new Date().toISOString(); const receipts = await readLocal<any[]>(storageKeys.privacyReceipts) ?? []; receipts.unshift({ id: `PR-${journey.id.slice(0, 8).toUpperCase()}`, journeyId: journey.id, purpose: "Safe Journey", startedAt: journey.started_at, completedAt, sharingStoppedAt: completedAt, sharedWith: ["Configured Guardian Circle"], precision: "No location points collected in this demo session", guardianTokenStatus: "No guardian location token created", retention: "Journey session remains in backend memory until server restart", createdAt: completedAt }); await writeLocal(storageKeys.privacyReceipts, receipts.slice(0, 25)); await removeLocal(storageKeys.activeJourney); await queueNonSensitiveEvent("journey.completed"); } setNotice(arrived ? "You’re marked safe. Guardians were updated and temporary monitoring ended." : `Safety protocol advanced to ${data.journey.escalation_level.replaceAll("_", " ")}; guardian alerts were submitted.`); });
  const safeword = () => act(async () => { if (!journey) return; const data = await post<any>("/journeys/safeword", { journey_id: journey.id, phrase: "blue notebook" }); if (data.matched) { setJourney({ ...journey, escalation_level: data.decision.escalation_level }); setNotice("SafeWord recognized. Trusted Circle workflow activated."); } });

  return <Screen><Eyebrow>JOURNEY GUARDIAN</Eyebrow><Title subtitle="Timed, battery-aware protection that stays in your control.">Plan your safe arrival</Title>
    {!journey ? <Card><Field label="Starting point" value={origin} onChangeText={setOrigin} placeholder="Where are you now?" /><Field label="Destination" value={destination} onChangeText={setDestination} placeholder="Where are you going?" /><View style={{ flexDirection: "row", gap: 8 }}><Pill label="10 min ETA" /><Pill label="1 trusted contact" tone="gray" /></View><Action label="Start journey protection" icon="shield-checkmark" onPress={start} disabled={busy || !origin.trim() || !destination.trim()} /></Card> :
    <><Card tone={journey.active ? "dark" : "mint"}><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><Pill label={journey.active ? "Journey active" : "Arrived safely"} /><Text style={{ color: journey.active ? "white" : colors.ink, fontWeight: "800" }}>{journey.power_mode} power</Text></View><Text style={{ color: journey.active ? "white" : colors.ink, fontSize: 24, fontWeight: "900" }}>{journey.origin} → {journey.destination}</Text><Text style={{ color: journey.active ? "#C9DED6" : colors.muted }}>Expected {new Date(journey.expected_arrival).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</Text><View style={{ flexDirection: "row", gap: 8 }}><Metric value={`${journey.battery_percent}%`} label="battery" /><Metric value={journey.missed_checkins} label="missed check-ins" /></View></Card>
    {journey.active ? <><Card tone="mint"><View style={{ flexDirection: "row", justifyContent: "space-between" }}><View><Text style={{ color: colors.primaryDark, fontWeight: "900", fontSize: 17 }}>Battery Guardian</Text><Text style={{ color: colors.muted }}>Tracking mode: Adaptive</Text></View><Pill label={`${batteryPolicy?.estimated_impact ?? "low"} impact`} /></View><Text style={{ color: colors.muted, lineHeight: 20 }}>{batteryPolicy?.reason ?? "Adaptive sampling avoids continuous GPS polling."}</Text><Text style={{ color: colors.primaryDark, fontSize: 12 }}>Accuracy: {batteryPolicy?.desired_accuracy ?? "balanced"} • Next sample: {batteryPolicy?.time_interval_s ?? 180}s • Policy v{batteryPolicy?.policy_version ?? "1.0"}</Text></Card><Card><Text style={{ color: colors.ink, fontWeight: "900", fontSize: 18 }}>Quick check-in</Text><Text style={{ color: colors.muted, lineHeight: 21 }}>Your location is temporary and the escalation policy is deterministic.</Text><Action label="I arrived safely" icon="checkmark-circle" onPress={() => checkin(true)} disabled={busy} /><Action label="Demo missed check-in" icon="time" variant="secondary" onPress={() => checkin(false)} disabled={busy} /><Action label="Demo SafeWord" icon="notifications" variant="danger" onPress={safeword} disabled={busy} /></Card></> : <Action label="Start another journey" onPress={() => { setJourney(null); setNotice(""); setBatteryPolicy(null); }} />}</>}
    {busy ? <Loading label="Updating your protection…" /> : null}{notice ? <Card tone="mint"><Text style={{ color: colors.primaryDark, fontWeight: "800", lineHeight: 21 }}>{notice}</Text></Card> : null}{error ? <ErrorBanner message={error} /> : null}
    <Text style={{ color: colors.muted, fontSize: 12, lineHeight: 18 }}>Emergency escalation always presents options; it never contacts services without your explicit action.</Text>
  </Screen>;
}
