import { useState } from "react";
import { Pressable, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { post } from "../lib/api";
import { Action, Card, colors, ErrorBanner, Eyebrow, Loading, Pill, Screen, Title } from "../lib/ui";

const items = [["trusted", "Trusted contact added", "Someone you choose can receive journey alerts"], ["plan", "Emergency plan ready", "You know who to call and where to go"], ["lock", "App lock enabled", "Sensitive information has an extra barrier"], ["notifications", "Private notifications", "Sensitive previews stay off the lock screen"], ["security", "Account security reviewed", "Passwords and recovery details are current"]] as const;
type Key = typeof items[number][0]; type Result = { score: number; missing: string[] };
export default function Readiness() {
  const [checked, setChecked] = useState<Record<Key, boolean>>({ trusted: true, plan: false, lock: true, notifications: false, security: true }); const [result, setResult] = useState<Result | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function run() { try { setBusy(true); setError(""); setResult(await post<Result>("/readiness", { trusted_contacts_count: checked.trusted ? 1 : 0, location_always_on: false, emergency_plan_configured: checked.plan, app_lock_enabled: checked.lock, notification_privacy_enabled: checked.notifications, account_security_reviewed: checked.security })); } catch (e) { setError(e instanceof Error ? e.message : "Assessment failed"); } finally { setBusy(false); } }
  return <Screen><Eyebrow>60-SECOND CHECKUP</Eyebrow><Title subtitle="No judgment—just practical steps you control.">How ready is your safety setup?</Title><Card>{items.map(([key, title, copy], i) => <Pressable key={key} onPress={() => { setChecked(v => ({ ...v, [key]: !v[key] })); setResult(null); }} style={{ flexDirection: "row", gap: 12, paddingVertical: 11, borderBottomWidth: i === items.length - 1 ? 0 : 1, borderBottomColor: colors.border }}><Ionicons name={checked[key] ? "checkmark-circle" : "ellipse-outline"} size={25} color={checked[key] ? colors.primary : colors.muted} /><View style={{ flex: 1 }}><Text style={{ color: colors.ink, fontWeight: "800", fontSize: 16 }}>{title}</Text><Text style={{ color: colors.muted, lineHeight: 19, marginTop: 2 }}>{copy}</Text></View></Pressable>)}<Action label="Calculate my readiness" icon="sparkles" onPress={run} disabled={busy} /></Card>{busy ? <Loading /> : null}{error ? <ErrorBanner message={error} retry={run} /> : null}{result ? <Card tone={result.score >= 75 ? "mint" : "plain"}><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><View><Text style={{ color: colors.muted, fontWeight: "800" }}>READINESS SCORE</Text><Text style={{ color: colors.ink, fontWeight: "900", fontSize: 42 }}>{result.score}<Text style={{ fontSize: 18 }}>/100</Text></Text></View><Pill label={result.score >= 75 ? "Strong foundation" : "Next steps ready"} tone={result.score >= 75 ? "green" : "gold"} /></View>{result.missing.length ? <View style={{ gap: 8 }}><Text style={{ color: colors.ink, fontWeight: "900", fontSize: 17 }}>Your next best actions</Text>{result.missing.map((m, i) => <View key={m} style={{ flexDirection: "row", gap: 10 }}><Text style={{ color: colors.primary, fontWeight: "900" }}>{i + 1}</Text><Text style={{ color: colors.ink, flex: 1, textTransform: "capitalize" }}>{m.replaceAll("_", " ")}</Text></View>)}</View> : <Text style={{ color: colors.primaryDark, fontWeight: "800" }}>You’ve covered every core readiness step.</Text>}</Card> : null}</Screen>;
}
