import { useState } from "react";
import { Linking, Pressable, Text, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import * as Location from "expo-location";
import { post } from "../lib/api";
import { Action, Card, colors, ErrorBanner, Eyebrow, Loading, Pill, Screen, Title } from "../lib/ui";

type Resource = { id: string; name: string; type: string; lat: number; lon: number; distance_km: number; phone?: string; website?: string };
type Response = { resources: Resource[]; provider: string; is_live: boolean; safety_note: string };
export default function Resources() {
  const [data, setData] = useState<Response | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function load() { try { setBusy(true); setError(""); const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== "granted") throw new Error("Location access was not granted. You can enable it in device settings."); const pos = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setData(await post<Response>("/resources/nearby-v2", { latitude: pos.coords.latitude, longitude: pos.coords.longitude, radius_km: 8 })); } catch (e) { setError(e instanceof Error ? e.message : "Could not find nearby support"); } finally { setBusy(false); } }
  return <Screen><Eyebrow>NEARBY SUPPORT</Eyebrow><Title subtitle="Hospitals, clinics, pharmacies, and police near your current location.">Help around you</Title>
    <Card tone="mint"><View style={{ flexDirection: "row", gap: 12, alignItems: "center" }}><Ionicons name="location" size={28} color={colors.primary} /><View style={{ flex: 1 }}><Text style={{ color: colors.ink, fontWeight: "900" }}>Location only when you ask</Text><Text style={{ color: colors.muted, lineHeight: 20 }}>Your coordinates are used for this search and are not stored.</Text></View></View><Action label={data ? "Refresh nearby places" : "Use my current location"} icon="navigate" onPress={load} disabled={busy} /></Card>
    {busy ? <Loading label="Finding support services nearby…" /> : null}{error ? <ErrorBanner message={error} retry={load} /> : null}
    {data ? <><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><Text style={{ color: colors.ink, fontWeight: "900", fontSize: 19 }}>{data.resources.length} places found</Text><Pill label={data.is_live ? "Live community data" : "Offline demo"} tone={data.is_live ? "green" : "gold"} /></View>{data.resources.map(r => <Card key={r.id}><View style={{ flexDirection: "row", justifyContent: "space-between", gap: 12 }}><View style={{ flex: 1 }}><Text style={{ color: colors.ink, fontWeight: "900", fontSize: 17 }}>{r.name}</Text><Text style={{ color: colors.muted, marginTop: 4, textTransform: "capitalize" }}>{r.type.replaceAll("_", " ")} • {r.distance_km} km away</Text></View><View style={{ width: 42, height: 42, borderRadius: 13, backgroundColor: colors.mint, alignItems: "center", justifyContent: "center" }}><Ionicons name={r.type === "police" ? "shield" : r.type === "pharmacy" ? "medkit" : "medical"} size={21} color={colors.primary} /></View></View><View style={{ flexDirection: "row", gap: 9 }}><Pressable onPress={() => Linking.openURL(`https://www.google.com/maps/dir/?api=1&destination=${r.lat},${r.lon}`)} style={{ flex: 1, borderRadius: 13, padding: 12, backgroundColor: colors.primary, alignItems: "center" }}><Text style={{ color: "white", fontWeight: "800" }}>Directions</Text></Pressable>{r.phone ? <Pressable onPress={() => Linking.openURL(`tel:${r.phone}`)} style={{ flex: 1, borderRadius: 13, padding: 12, borderColor: colors.border, borderWidth: 1, alignItems: "center" }}><Text style={{ color: colors.ink, fontWeight: "800" }}>Call</Text></Pressable> : null}</View></Card>)}<Text style={{ color: colors.muted, fontSize: 12, lineHeight: 18 }}>Source: {data.provider}. {data.safety_note}</Text></> : null}
  </Screen>;
}
