import { useEffect, useRef, useState } from "react";
import { Linking, Pressable, Text, View } from "react-native";
import * as Battery from "expo-battery";
import { authPost } from "../lib/api";
import { Action, Card, colors, ErrorBanner, Eyebrow, Loading, Pill, Screen, Title } from "../lib/ui";
type Session = { id: string; status: string; guardians_notified: string[]; location_session_expires_at: string; emergency_services_contacted: boolean };
export default function SOS() {
  const [holding, setHolding] = useState(false); const [countdown, setCountdown] = useState<number | null>(null); const [session, setSession] = useState<Session | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const holdTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  function beginHold() { setHolding(true); holdTimer.current = setTimeout(() => { setHolding(false); setCountdown(3); }, 1200); }
  function stopHold() { setHolding(false); if (holdTimer.current) clearTimeout(holdTimer.current); }
  useEffect(() => { if (countdown === null) return; if (countdown === 0) { setCountdown(null); activate(); return; } const timer = setTimeout(() => setCountdown(v => v === null ? null : v - 1), 1000); return () => clearTimeout(timer); }, [countdown]);
  async function activate() { try { setBusy(true); const level = await Battery.getBatteryLevelAsync(); setSession(await authPost<Session>("/sos", { battery_percent: level < 0 ? null : Math.round(level * 100) })); } catch (e) { setError(e instanceof Error ? e.message : "SOS could not start"); } finally { setBusy(false); } }
  async function cancel() { if (!session) return; try { setBusy(true); setSession(await authPost<Session>(`/sos/${session.id}/cancel`, { reason: "user_safe" })); } catch (e) { setError(e instanceof Error ? e.message : "SOS could not be cancelled"); } finally { setBusy(false); } }
  if (session?.status === "active") return <Screen><Eyebrow>HIGH-CONTRAST EMERGENCY STATE</Eyebrow><Card tone="danger"><Pill label="SOS active" tone="red" /><Text style={{ color: colors.danger, fontWeight: "900", fontSize: 34 }}>Stay in control</Text><Text style={{ color: colors.ink, lineHeight: 22 }}>{session.guardians_notified.length ? `SOS messages were submitted for ${session.guardians_notified.join(", ")}. Check each provider result for final delivery status.` : "No guardians are configured. Add one from Guardian Circle."}</Text><Text style={{ color: colors.muted }}>Temporary sharing expires {new Date(session.location_session_expires_at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}.</Text></Card><Action label="Call emergency services" icon="call" variant="danger" onPress={() => Linking.openURL("tel:911")} /><Action label="I’m safe — end SOS" icon="checkmark-circle" variant="secondary" onPress={cancel} disabled={busy} /><Text style={{ color: colors.muted, fontSize: 12 }}>Shakti360 has not contacted emergency services. The call button requires your explicit action.</Text>{busy ? <Loading /> : null}{error ? <ErrorBanner message={error} /> : null}</Screen>;
  return <Screen><Eyebrow>EXPLICIT SOS</Eyebrow><Title subtitle="Designed to activate in two interactions, with a cancellation window.">Need urgent help?</Title><Card tone="danger"><Text style={{ color: colors.ink, fontSize: 18, fontWeight: "900" }}>Press and hold to begin</Text><Text style={{ color: colors.muted, lineHeight: 21 }}>After holding, you have three seconds to cancel. Configured guardians are notified; emergency services are never contacted automatically.</Text><Pressable accessibilityRole="button" accessibilityLabel="Press and hold to activate SOS" onPressIn={beginHold} onPressOut={stopHold} style={({ pressed }) => ({ height: 180, width: 180, borderRadius: 90, alignSelf: "center", alignItems: "center", justifyContent: "center", backgroundColor: pressed || holding ? "#8F271F" : colors.danger, borderWidth: 10, borderColor: "#F5CBC5" })}><Text style={{ color: "white", fontSize: 34, fontWeight: "900" }}>{holding ? "HOLD…" : "SOS"}</Text><Text style={{ color: "white", fontWeight: "700" }}>hold 1.2 sec</Text></Pressable></Card>{countdown !== null ? <Card tone="dark"><Text style={{ color: "white", fontWeight: "900", fontSize: 28, textAlign: "center" }}>Activating in {countdown}</Text><Action label="Cancel" variant="secondary" icon="close" onPress={() => setCountdown(null)} /></Card> : null}{session?.status === "cancelled" ? <Card tone="mint"><Text style={{ color: colors.primaryDark, fontWeight: "900" }}>SOS ended. You are marked safe.</Text></Card> : null}{busy ? <Loading label="Starting temporary SOS session…" /> : null}{error ? <ErrorBanner message={error} /> : null}</Screen>;
}
